import { CardDetail } from "@/types/card.types";

export const DEMO_TEMPLATES_MAP: Record<string, CardDetail> = {
  // ─────────────────────────────────────────────────────────────────────────────
  // 01. Á ĐÔNG CUNG ĐÌNH SƠN MÀI HOÀNG GIA (MINH KHÔI & NGỌC HÂN)
  // ─────────────────────────────────────────────────────────────────────────────
  "wedding-heritage-crimson-gold": {
    id: "demo-heritage-crimson-gold",
    slug: "wedding-heritage-crimson-gold",
    cardCategory: "WEDDING",
    status: "ACTIVE",
    openingEffect: "NONE",
    fallingEffect: "PETAL",
    musicUrl: "/music/le-duong.mp3",
    isAutoPlay: true,
    primaryColor: "#8B1E2D",
    fontFamily: "Playfair Display",
    greetingMessage: "“Trăm năm tình viên mãn — Bạc đầu nghĩa phu thê” Trân trọng kính mời quý khách đến chung vui lễ thành hôn cùng gia đình chúng tôi!",
    template: { slug: "wedding-heritage-crimson-gold" },
    categoryData: {
      cardCategory: "WEDDING",
      heroSubtitle: "TRÂN TRỌNG BÁO HỶ",
      invitationTitle: "LỄ THÀNH HÔN & VU QUY",
      coverPhotoUrl: "/images/templates/template-01-heritage.png",
      greeting: "“Trăm năm tình viên mãn — Bạc đầu nghĩa phu thê”",
      groom: {
        fullName: "Nguyễn Minh Khôi",
        shortName: "Minh Khôi",
        birthOrder: "Trưởng nam",
        avatarUrl: "/images/demo/groom-avatar.png",
        parents: { fatherName: "Nguyễn Văn Hùng", motherName: "Trần Thị Mai" },
        story: "Chàng trai yêu nghệ thuật truyền thống, ấm áp và luôn trân trọng gia đình.",
      },
      bride: {
        fullName: "Lê Ngọc Hân",
        shortName: "Ngọc Hân",
        birthOrder: "Út nữ",
        avatarUrl: "/images/demo/bride-avatar.png",
        parents: { fatherName: "Lê Quốc Bảo", motherName: "Phạm Thu Cúc" },
        story: "Cô gái dịu dàng, nết na, yêu nét đẹp Á Đông và hoa sen.",
      },
      loveStory: [
        { title: "Chạm Ánh Mắt", date: "2021", description: "Lần đầu gặp gỡ tại hội hoa xuân phố cổ Hà Nội." },
        { title: "Gắn Kết Yêu Thương", date: "2024", description: "Cùng nhau vượt qua nhiều thăng trầm để trọn vẹn bên nhau." },
        { title: "Trọn Đời Chung Đôi", date: "2026", description: "Chính thức nên duyên vợ chồng trước sự chứng kiến của hai họ." },
      ],
    },
    events: [
      {
        id: "ev-11",
        eventName: "Lễ Vu Quy (Nhà Gái)",
        eventDate: new Date("2026-11-20T08:30:00Z"),
        lunarDate: "Ngày 12 Tháng 10 Năm Bính Ngọ",
        venueName: "Tư Gia Nhà Gái",
        address: "Số 88 Phố Huế, Phường Hàng Bài, Hoàn Kiếm, Hà Nội",
        mapUrl: "https://maps.google.com",
      },
      {
        id: "ev-12",
        eventName: "Lễ Thành Hôn & Tiệc Cưới",
        eventDate: new Date("2026-11-20T17:30:00Z"),
        lunarDate: "Ngày 12 Tháng 10 Năm Bính Ngọ",
        venueName: "Trung Tâm Tiệc Cưới Hoàng Gia",
        address: "Số 194 Hoàng Văn Thụ, Phường 9, Quận Phú Nhuận, TP. HCM",
        mapUrl: "https://maps.google.com",
      },
    ],
    photos: [
      { id: "p-1", url: "/images/demo/couple-aodai.png", caption: "Lễ gia tiên truyền thống Á Đông", isCover: true },
      { id: "p-2", url: "/images/demo/couple-cover.png", caption: "Trăm năm trọn vẹn nghĩa phu thê" },
      { id: "p-3", url: "/images/demo/couple-studio.png", caption: "Nụ cười rạng rỡ ngày trọng đại" },
      { id: "p-4", url: "/images/demo/groom-avatar.png", caption: "Chú rể Minh Khôi" },
      { id: "p-5", url: "/images/demo/bride-avatar.png", caption: "Cô dâu Ngọc Hân" },
      { id: "p-6", url: "/images/templates/template-01-heritage.png", caption: "Khoảnh khắc hoàng gia" },
    ],
    bankingPrimary: { bankCode: "MB", accountNumber: "9999888899", accountName: "NGUYEN MINH KHOI" },
    bankingSecondary: { bankCode: "VCB", accountNumber: "8888999988", accountName: "LE NGOC HAN" },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 02. TẠP CHÍ HÀN QUỐC EDITORIAL (CÔNG VINH & HẢI YẾN)
  // ─────────────────────────────────────────────────────────────────────────────
  "wedding-modern-editorial-magazine": {
    id: "demo-modern-editorial-magazine",
    slug: "wedding-modern-editorial-magazine",
    cardCategory: "WEDDING",
    status: "ACTIVE",
    openingEffect: "NONE",
    fallingEffect: "PETAL",
    musicUrl: "/music/ngay-dau-tien.mp3",
    isAutoPlay: true,
    primaryColor: "#543A2C",
    fontFamily: "Inter",
    greetingMessage: "“Chúng ta đã cùng nhau đi qua nhiều thăng trầm để nhận ra rằng được ở bên nhau là điều quý giá nhất... Hôm nay chúng mình chính thức gọi nhau hai tiếng Vợ - Chồng.”",
    template: { slug: "wedding-modern-editorial-magazine" },
    categoryData: {
      cardCategory: "WEDDING",
      heroSubtitle: "MODERN EDITORIAL WEDDING",
      invitationTitle: "THIỆP MỜI THÀNH HÔN",
      coverPhotoUrl: "/images/demo/korean-hero.png",
      greeting: "“Một hành trình mới của chúng mình bắt đầu từ hôm nay”",
      groom: {
        fullName: "Phạm Công Vinh",
        shortName: "Công Vinh",
        birthOrder: "Trưởng nam",
        avatarUrl: "/images/demo/korean-groom.png",
        parents: { fatherName: "Phạm Minh Toàn", motherName: "Lại Thị Tám" },
        story: "Kiến trúc sư trẻ, say mê thiết kế và luôn là chỗ dựa vững chắc.",
      },
      bride: {
        fullName: "Nguyễn Hải Yến",
        shortName: "Hải Yến",
        birthOrder: "Út nữ",
        avatarUrl: "/images/demo/korean-bride.png",
        parents: { fatherName: "Nguyễn Tiến Minh", motherName: "Hoàng Cẩm Vân" },
        story: "Biên tập viên thời trang thanh lịch, yêu sự lãng mạn tinh tế.",
      },
      loveStory: [
        { title: "First Meeting", date: "2020", description: "Buổi chiều thu bên quán cà phê nhỏ phố cổ." },
        { title: "Proposal in Da Lat", date: "2023", description: "Dưới ánh hoàng hôn đồi thông, em đã mỉm cười gật đầu." },
        { title: "Happy Wedding", date: "2026", description: "Cùng viết tiếp cuốn nhật ký hạnh phúc của cuộc đời." },
      ],
    },
    events: [
      {
        id: "ev-21",
        eventName: "Hôn Lễ & Bữa Tiệc Thân Mật",
        eventDate: new Date("2026-12-27T11:00:00Z"),
        lunarDate: "Ngày 10 Tháng 11 Năm Bính Ngọ",
        venueName: "TƯ GIA NHÀ TRAI",
        address: "16 P. Phúc Minh, Phúc Diễn, Bắc Từ Liêm, TP. Hà Nội",
        mapUrl: "https://maps.google.com",
      },
    ],
    photos: [
      { id: "p-21", url: "/images/demo/korean-hero.png", caption: "Cover Editorial 28.12.2026", isCover: true },
      { id: "p-22", url: "/images/demo/korean-bride.png", caption: "Cô dâu Hải Yến rạng rỡ" },
      { id: "p-23", url: "/images/demo/korean-groom.png", caption: "Chú rể Công Vinh lịch lãm" },
      { id: "p-24", url: "/images/demo/korean-calendar.png", caption: "Wedding Moment & Calendar" },
    ],
    bankingPrimary: { bankCode: "TECHCOMBANK", accountNumber: "1903338888", accountName: "PHAM CONG VINH" },
    bankingSecondary: { bankCode: "MB", accountNumber: "0988776655", accountName: "NGUYEN HAI YEN" },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 03. SWEET PINK LÃNG MẠN (QUỐC HUY & MAI ANH)
  // ─────────────────────────────────────────────────────────────────────────────
  "wedding-sweet-editorial-romance": {
    id: "demo-sweet-editorial-romance",
    slug: "wedding-sweet-editorial-romance",
    cardCategory: "WEDDING",
    status: "ACTIVE",
    openingEffect: "NONE",
    fallingEffect: "HEART",
    musicUrl: "/music/beautiful-in-white.mp3",
    isAutoPlay: true,
    primaryColor: "#B84A39",
    fontFamily: "Great Vibes",
    greetingMessage: "“Cảm ơn bạn đã dành thời gian quý báu để cùng chúng mình chung vui trong ngày đặc biệt này...”",
    template: { slug: "wedding-sweet-editorial-romance" },
    categoryData: {
      cardCategory: "WEDDING",
      heroSubtitle: "SWEET ROMANCE INVITATION",
      invitationTitle: "LỄ THÀNH HÔN",
      coverPhotoUrl: "/images/demo/sweet-romance-couple.jpg",
      greeting: "“Khoảnh khắc hạnh phúc nhất là khi tìm thấy một nửa yêu thương của cuộc đời”",
      groom: {
        fullName: "Phạm Quốc Huy",
        shortName: "Quốc Huy",
        birthOrder: "Trưởng nam",
        avatarUrl: "/images/demo/sweet-romance-couple.jpg",
        parents: { fatherName: "Phạm Quang Hải", motherName: "Định Thị Mai" },
        story: "Chàng trai chân thành, yêu thiên nhiên và luôn mang đến sự bình yên.",
      },
      bride: {
        fullName: "Nguyễn Mai Anh",
        shortName: "Mai Anh",
        birthOrder: "Thứ nữ",
        avatarUrl: "/images/demo/sweet-romance-couple.jpg",
        parents: { fatherName: "Nguyễn Tiến Minh", motherName: "Lê Thị Hải Yến" },
        story: "Cô gái ngọt ngào, tinh tế, thích làm bánh và hoa cỏ đồng nội.",
      },
      loveStory: [
        { title: "Duyên Khởi", date: "2019", description: "Tình cờ quen nhau trong một chuyến dã ngoại vùng cao." },
        { title: "Lời Hẹn Ước", date: "2024", description: "Chiếc nhẫn cầu hôn dưới ánh nến lãng mạn." },
        { title: "Về Chung Một Nhà", date: "2026", description: "Bắt đầu chương mới ngọt ngào bên nhau." },
      ],
    },
    events: [
      {
        id: "ev-31",
        eventName: "Tiệc Mừng Lễ Thành Hôn",
        eventDate: new Date("2026-12-24T10:30:00Z"),
        lunarDate: "Ngày 17 Tháng 11 Năm Bính Ngọ",
        venueName: "TRỐNG ĐỒNG PALACE",
        address: "08A Lý Văn Phúc, P. Cát Linh, Đống Đa, TP. Hà Nội",
        mapUrl: "https://maps.google.com",
      },
      {
        id: "ev-32",
        eventName: "Lễ Vu Quy (Tại Nhà Gái)",
        eventDate: new Date("2026-12-23T09:00:00Z"),
        lunarDate: "Ngày 16 Tháng 11 Năm Bính Ngọ",
        venueName: "Tư Gia Nhà Gái",
        address: "Số 26 Đường Thanh Niên, Tây Hồ, TP. Hà Nội",
        mapUrl: "https://maps.google.com",
      },
    ],
    photos: [
      { id: "p-31", url: "/images/demo/sweet-romance-couple.jpg", caption: "Sweet Pink Romance", isCover: true },
      { id: "p-32", url: "/images/templates/template-03-sweet-pink.png", caption: "Sweet Pink Card" },
      { id: "p-33", url: "/images/demo/couple-cover.png", caption: "Nụ cười rạng rỡ" },
      { id: "p-34", url: "/images/demo/sweet-romance-couple.jpg", caption: "Cô dâu Mai Anh" },
      { id: "p-35", url: "/images/demo/sweet-romance-couple.jpg", caption: "Chú rể Quốc Huy" },
    ],
    bankingPrimary: { bankCode: "MB", accountNumber: "0345678901", accountName: "PHAM QUOC HUY" },
    bankingSecondary: { bankCode: "MB", accountNumber: "0345678902", accountName: "NGUYEN MAI ANH" },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 04. QUÝ TỘC ĐỎ RƯỢU MARSALA & CỔNG VÒM (NGUYỄN MINH & BÙI PHƯƠNG)
  // ─────────────────────────────────────────────────────────────────────────────
  "wedding-crimson-wine-marsala": {
    id: "demo-crimson-wine-marsala",
    slug: "wedding-crimson-wine-marsala",
    cardCategory: "WEDDING",
    status: "ACTIVE",
    openingEffect: "NONE",
    fallingEffect: "PETAL",
    musicUrl: "/music/die-with-a-smile.mp3",
    isAutoPlay: true,
    primaryColor: "#6B1724",
    fontFamily: "Playfair Display",
    greetingMessage: "“Hôn duyên nên nghĩa vợ chồng — Trăm năm giữ trọn tấm lòng cùng nhau. Trân trọng kính mời quý khách đến dự tiệc cưới của gia đình chúng tôi!”",
    template: { slug: "wedding-crimson-wine-marsala" },
    categoryData: {
      cardCategory: "WEDDING",
      heroSubtitle: "WELCOME TO OUR WEDDING",
      invitationTitle: "THƯ MỜI TIỆC CƯỚI",
      coverPhotoUrl: "/images/demo/marsala-wine-couple.jpg",
      greeting: "“Duyên trời định, tình người thắt — Hạnh phúc đong đầy muôn thuở”",
      groom: {
        fullName: "Nguyễn Minh",
        shortName: "Nguyễn Minh",
        birthOrder: "Trưởng nam",
        avatarUrl: "/images/demo/marsala-wine-couple.jpg",
        parents: { fatherName: "Nguyễn Trọng Đại", motherName: "Trần Thị Lan" },
        story: "Phong thái lịch lãm, điềm đạm và luôn dành trọn sự yêu thương.",
      },
      bride: {
        fullName: "Bùi Phương",
        shortName: "Bùi Phương",
        birthOrder: "Út nữ",
        avatarUrl: "/images/demo/marsala-wine-couple.jpg",
        parents: { fatherName: "Bùi Văn Thành", motherName: "Lê Thị Thu" },
        story: "Quyến rũ, tinh tế, nụ cười toả nắng và tâm hồn sâu sắc.",
      },
      loveStory: [
        { title: "Định Mệnh", date: "2020", description: "Cuộc gặp gỡ tình cờ nhưng viết nên cả một trang đời." },
        { title: "Gắn Bó", date: "2023", description: "Bên nhau qua bao miền đất và sẻ chia mọi mơ ước." },
        { title: "Hôn Lễ", date: "2026", description: "Thời khắc thiêng liêng nắm chặt tay bước vào lễ đường." },
      ],
    },
    events: [
      {
        id: "ev-41",
        eventName: "Tiệc Cưới Nhà Trai",
        eventDate: new Date("2026-12-20T16:00:00Z"),
        lunarDate: "Ngày 06 Tháng 11 Năm Bính Ngọ",
        venueName: "Tư Gia Nhà Trai",
        address: "Khu Phố Xuân Thượng, Phường Quảng Vinh, Nam Sầm Sơn, Thanh Hóa",
        mapUrl: "https://maps.google.com",
      },
      {
        id: "ev-42",
        eventName: "Tiệc Cưới Nhà Gái",
        eventDate: new Date("2026-12-19T16:00:00Z"),
        lunarDate: "Ngày 05 Tháng 11 Năm Bính Ngọ",
        venueName: "Tư Gia Nhà Gái",
        address: "Xóm 9, Thôn Ngũ Phúc, Xã Tống Trân, Huyện Phù Cừ, Tỉnh Hưng Yên",
        mapUrl: "https://maps.google.com",
      },
    ],
    photos: [
      { id: "p-41", url: "/images/demo/marsala-wine-couple.jpg", caption: "Marsala Arch Cover", isCover: true },
      { id: "p-42", url: "/images/templates/template-04-marsala.png", caption: "Marsala Card" },
      { id: "p-43", url: "/images/demo/couple-cover.png", caption: "Our Vows" },
      { id: "p-44", url: "/images/demo/marsala-wine-couple.jpg", caption: "Chú rể Nguyễn Minh" },
      { id: "p-45", url: "/images/demo/marsala-wine-couple.jpg", caption: "Cô dâu Bùi Phương" },
    ],
    bankingPrimary: { bankCode: "BIDV", accountNumber: "1234567890", accountName: "NGUYEN MINH" },
    bankingSecondary: { bankCode: "TECHCOMBANK", accountNumber: "1908765432", accountName: "BUI PHUONG" },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 05. RUSTIC XANH RÊU THIÊN NHIÊN & HOA DẠI (TUẤN MINH & MAI LAN)
  // ─────────────────────────────────────────────────────────────────────────────
  "wedding-forest-green-botanical": {
    id: "demo-forest-green-botanical",
    slug: "wedding-forest-green-botanical",
    cardCategory: "WEDDING",
    status: "ACTIVE",
    openingEffect: "NONE",
    fallingEffect: "PETAL",
    musicUrl: "/music/a-thousand-years.mp3",
    isAutoPlay: true,
    primaryColor: "#3D4A34",
    fontFamily: "Outfit",
    greetingMessage: "“Em là tình yêu anh muốn giữ — Anh là hạnh phúc em muốn trao. Trân trọng kính mời bạn đến chung vui trong ngày đặc biệt của chúng mình!”",
    template: { slug: "wedding-forest-green-botanical" },
    categoryData: {
      cardCategory: "WEDDING",
      heroSubtitle: "WE GOT MARRIED",
      invitationTitle: "THIỆP MỜI DỰ TIỆC CƯỚI",
      coverPhotoUrl: "/images/demo/forest-botanical-couple.jpg",
      greeting: "“Giữa muôn ngàn hoa dại của thảo nguyên, anh chọn đoá hoa dịu dàng nhất là em”",
      groom: {
        fullName: "Tuấn Minh",
        shortName: "Tuấn Minh",
        birthOrder: "Trưởng nam",
        avatarUrl: "/images/demo/forest-botanical-couple.jpg",
        parents: { fatherName: "Nguyễn Văn Tư", motherName: "Lê Thị Mai" },
        story: "Yêu cây cỏ, thích khám phá những cung đường thiên nhiên hoang sơ.",
      },
      bride: {
        fullName: "Mai Lan",
        shortName: "Mai Lan",
        birthOrder: "Út nữ",
        avatarUrl: "/images/demo/forest-botanical-couple.jpg",
        parents: { fatherName: "Nguyễn Trí Thanh", motherName: "Lê Thị Hải" },
        story: "Hoạ sĩ tự do với nụ cười hiền, yêu động vật và cuộc sống mộc mạc.",
      },
      loveStory: [
        { title: "Rừng Thông Mơ Màng", date: "2021", description: "Bắt gặp nhau trong buổi cắm trại mùa mưa." },
        { title: "Đồng Hành", date: "2024", description: "Cùng xây dựng tổ ấm nhỏ tràn ngập cây xanh." },
        { title: "Lời Thề Nguyện", date: "2026", description: "Nắm tay nhau bước đi trọn vẹn kiếp này." },
      ],
    },
    events: [
      {
        id: "ev-51",
        eventName: "Bữa Cơm Thân Mật (Nhà Gái)",
        eventDate: new Date("2026-08-02T10:30:00Z"),
        lunarDate: "Ngày 20 Tháng 06 Năm Bính Ngọ",
        venueName: "Tư Gia Nhà Gái",
        address: "Xóm 5, Xã Phú Cát, Huyện Quốc Oai, TP. Hà Nội",
        mapUrl: "https://maps.google.com",
      },
      {
        id: "ev-52",
        eventName: "Tham Dự Hôn Lễ (Nhà Trai)",
        eventDate: new Date("2026-08-02T12:30:00Z"),
        lunarDate: "Ngày 20 Tháng 06 Năm Bính Ngọ",
        venueName: "Tư Gia Nhà Trai",
        address: "Khu Đô Thị Định Công, Quận Hoàng Mai, TP. Hà Nội",
        mapUrl: "https://maps.google.com",
      },
    ],
    photos: [
      { id: "p-51", url: "/images/demo/forest-botanical-couple.jpg", caption: "Rustic Forest Botanical", isCover: true },
      { id: "p-52", url: "/images/templates/template-05-forest.png", caption: "Forest Invitation Card" },
      { id: "p-53", url: "/images/demo/couple-cover.png", caption: "Giữa thiên nhiên hoa cỏ" },
      { id: "p-54", url: "/images/demo/forest-botanical-couple.jpg", caption: "Chú rể Tuấn Minh" },
      { id: "p-55", url: "/images/demo/forest-botanical-couple.jpg", caption: "Cô dâu Mai Lan" },
    ],
    bankingPrimary: { bankCode: "AGRIBANK", accountNumber: "2200112233", accountName: "TUAN MINH" },
    bankingSecondary: { bankCode: "VIETINBANK", accountNumber: "1010202030", accountName: "MAI LAN" },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 06. HOA SEN THANH KHIẾT BÁO HỶ THUẦN VIỆT (MINH HẰNG & ĐỨC HIỂN)
  // ─────────────────────────────────────────────────────────────────────────────
  "wedding-pure-lotus-heritage": {
    id: "demo-pure-lotus-heritage",
    slug: "wedding-pure-lotus-heritage",
    cardCategory: "WEDDING",
    status: "ACTIVE",
    openingEffect: "NONE",
    fallingEffect: "PETAL",
    musicUrl: "/music/i-do.mp3",
    isAutoPlay: true,
    primaryColor: "#3B5E43",
    fontFamily: "Playfair Display",
    greetingMessage: "“Gần bùn mà chẳng hôi tanh mùi bùn — Tình nồng thắm thiết trọn đời bên nhau. Trân trọng kính báo tin vui cùng người thân, bạn bè!”",
    template: { slug: "wedding-pure-lotus-heritage" },
    categoryData: {
      cardCategory: "WEDDING",
      heroSubtitle: "THIỆP BÁO HỶ",
      invitationTitle: "LỄ BÁO HỶ & THÀNH HÔN",
      coverPhotoUrl: "/images/demo/lotus-heritage-couple.jpg",
      greeting: "“Trân trọng kính báo tới Quý Khách, bạn bè và người thân: Lễ kết hôn của hai con chúng tôi đã được cử hành chu toàn và trọn vẹn.”",
      groom: {
        fullName: "Đức Hiển",
        shortName: "Đức Hiển",
        birthOrder: "Trưởng nam",
        avatarUrl: "/images/demo/lotus-heritage-couple.jpg",
        parents: { fatherName: "Trần Đức Nam", motherName: "Lê Thị Xuân" },
        story: "Kỹ sư công nghệ đĩnh đạc, luôn giữ gìn các giá trị cội nguồn văn hoá.",
      },
      bride: {
        fullName: "Minh Hằng",
        shortName: "Minh Hằng",
        birthOrder: "Út nữ",
        avatarUrl: "/images/demo/lotus-heritage-couple.jpg",
        parents: { fatherName: "Nguyễn Văn Phúc", motherName: "Hoàng Thị Huệ" },
        story: "Cô gái Hà Thành đoan trang, yêu áo dài truyền thống và hương sen Tây Hồ.",
      },
      loveStory: [
        { title: "Hương Sen Đầu Mùa", date: "2020", description: "Bên đầm sen Quảng An buổi sớm sương mai trong trẻo." },
        { title: "Tri Kỷ", date: "2023", description: "Cùng chia sẻ những ước mơ và hoài bão lớn." },
        { title: "Báo Hỷ", date: "2026", description: "Trân trọng báo tin vui kết duyên trăm năm." },
      ],
    },
    events: [
      {
        id: "ev-61",
        eventName: "Tiệc Mừng Báo Hỷ",
        eventDate: new Date("2026-11-15T11:00:00Z"),
        lunarDate: "Ngày 07 Tháng 10 Năm Bính Ngọ",
        venueName: "TRUNG TÂM TIỆC CƯỚI HOA SEN",
        address: "Số 68 Đường Tây Hồ, Phường Quảng An, Quận Tây Hồ, Hà Nội",
        mapUrl: "https://maps.google.com",
      },
    ],
    photos: [
      { id: "p-61", url: "/images/demo/lotus-heritage-couple.jpg", caption: "Hoa Sen Báo Hỷ Cover", isCover: true },
      { id: "p-62", url: "/images/templates/template-06-lotus.png", caption: "Thiệp Báo Hỷ" },
      { id: "p-63", url: "/images/demo/couple-cover.png", caption: "Ngày chung đôi trăm năm" },
      { id: "p-64", url: "/images/demo/lotus-heritage-couple.jpg", caption: "Chú rể Đức Hiển" },
      { id: "p-65", url: "/images/demo/lotus-heritage-couple.jpg", caption: "Cô dâu Minh Hằng" },
    ],
    bankingPrimary: { bankCode: "VCB", accountNumber: "001100223344", accountName: "DUC HIEN" },
    bankingSecondary: { bankCode: "MB", accountNumber: "0999888777", accountName: "MINH HANG" },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 07. ĐIỆN ẢNH LOOKBOOK TẠP CHÍ VOGUE (THÙY LINH & QUANG HUY)
  // ─────────────────────────────────────────────────────────────────────────────
  "wedding-cinematic-editorial": {
    id: "demo-cinematic-editorial",
    slug: "wedding-cinematic-editorial",
    cardCategory: "WEDDING",
    status: "ACTIVE",
    openingEffect: "NONE",
    fallingEffect: "PETAL",
    musicUrl: "/music/perfect.mp3",
    isAutoPlay: true,
    primaryColor: "#1C1C1C",
    fontFamily: "Cinzel",
    greetingMessage: "“Một cái chạm mắt giữa đồi thông mộng mơ... đã mở ra một tình yêu vĩnh cửu của cuộc đời. Kính mời quý khách đến dự tiệc cưới của chúng tôi!”",
    template: { slug: "wedding-cinematic-editorial" },
    categoryData: {
      cardCategory: "WEDDING",
      heroSubtitle: "CINEMATIC FILM & VOGUE LOOKBOOK",
      invitationTitle: "WEDDING INVITATION",
      coverPhotoUrl: "/images/demo/cinematic-vogue-couple.jpg",
      greeting: "“Tình yêu của chúng mình tựa như một thước phim điện ảnh lãng mạn nhất”",
      groom: {
        fullName: "Quang Huy",
        shortName: "Quang Huy",
        birthOrder: "Trưởng nam",
        avatarUrl: "/images/demo/cinematic-vogue-couple.jpg",
        parents: { fatherName: "Vũ Quang Tuấn", motherName: "Lê Minh Nguyệt" },
        story: "Đạo diễn hình ảnh tài năng, đam mê màu sắc điện ảnh và sự hoàn mỹ.",
      },
      bride: {
        fullName: "Thùy Linh",
        shortName: "Thùy Linh",
        birthOrder: "Út nữ",
        avatarUrl: "/images/demo/cinematic-vogue-couple.jpg",
        parents: { fatherName: "Nguyễn Thành Chung", motherName: "Đỗ Bích Thảo" },
        story: "Nhà thiết kế nội thất phong cách Bắc Âu, yêu ánh sáng tự nhiên.",
      },
      loveStory: [
        { title: "Chapter 01: The Encounter", date: "2021", description: "Bắt gặp ánh mắt nhau tại phim trường mùa đông." },
        { title: "Chapter 02: Fall In Love", date: "2023", description: "Những chuyến đi không có đích đến, chỉ cần có nhau." },
        { title: "Chapter 03: The Vows", date: "2026", description: "Thời khắc lời thề ước vang lên dưới ánh đèn rực rỡ." },
      ],
    },
    events: [
      {
        id: "ev-71",
        eventName: "Hôn Lễ & Bữa Tiệc Tối Tinh Tế",
        eventDate: new Date("2026-11-19T10:30:00Z"),
        lunarDate: "Ngày 11 Tháng 10 Năm Bính Ngọ",
        venueName: "PROMEX CENTER",
        address: "Số 114 Mai Hắc Đế, Phường Lê Đại Hành, Quận Hai Bà Trưng, Hà Nội",
        mapUrl: "https://maps.google.com",
      },
    ],
    photos: [
      { id: "p-71", url: "/images/demo/cinematic-vogue-couple.jpg", caption: "Cinematic Vogue Cover", isCover: true },
      { id: "p-72", url: "/images/templates/template-07-cinematic.png", caption: "Vogue Magazine Layout" },
      { id: "p-73", url: "/images/demo/couple-studio.png", caption: "Chapter 02: Fall In Love" },
      { id: "p-74", url: "/images/demo/cinematic-vogue-couple.jpg", caption: "Chú rể Quang Huy" },
      { id: "p-75", url: "/images/demo/cinematic-vogue-couple.jpg", caption: "Cô dâu Thùy Linh" },
    ],
    bankingPrimary: { bankCode: "TECHCOMBANK", accountNumber: "1903337777", accountName: "QUANG HUY" },
    bankingSecondary: { bankCode: "MB", accountNumber: "0912345678", accountName: "THUY LINH" },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 08. SUỐI NGUỒN HỒ NƯỚC THIÊN NHIÊN (NGUYỄN DƯƠNG & KHÁNH THY)
  // ─────────────────────────────────────────────────────────────────────────────
  "wedding-alpine-lake-romance": {
    id: "demo-alpine-lake-romance",
    slug: "wedding-alpine-lake-romance",
    cardCategory: "WEDDING",
    status: "ACTIVE",
    openingEffect: "NONE",
    fallingEffect: "SNOW",
    musicUrl: "/music/mot-nha.mp3",
    isAutoPlay: true,
    primaryColor: "#2B6B6D",
    fontFamily: "Playfair Display",
    greetingMessage: "“Trong đời mỗi người, sẽ luôn có một khoảnh khắc cần kiên định với lựa chọn của chính mình... Khoảnh khắc ấy, chính là hiện tại có bạn bên cạnh ❤️”",
    template: { slug: "wedding-alpine-lake-romance" },
    categoryData: {
      cardCategory: "WEDDING",
      heroSubtitle: "ALPINE LAKE ROMANCE",
      invitationTitle: "LỄ CƯỚI BÊN HỒ",
      coverPhotoUrl: "/images/demo/alpine-lake-couple.jpg",
      greeting: "“Trước mặt hồ trong vắt và đất trời bao la, chúng mình nguyện cùng nhau đi hết cuộc đời”",
      groom: {
        fullName: "Nguyễn Dương",
        shortName: "Nguyễn Dương",
        birthOrder: "Trưởng nam",
        avatarUrl: "/images/demo/alpine-lake-couple.jpg",
        parents: { fatherName: "Nguyễn Văn Thắng", motherName: "Trần Thị Ánh" },
        story: "Chàng trai yêu thể thao mạo hiểm, phóng khoáng và luôn đầy ắp năng lượng.",
      },
      bride: {
        fullName: "Khánh Thy",
        shortName: "Khánh Thy",
        birthOrder: "Thứ nữ",
        avatarUrl: "/images/demo/alpine-lake-couple.jpg",
        parents: { fatherName: "Lê Hữu Đạt", motherName: "Phạm Hồng Vân" },
        story: "Nữ bác sĩ tâm lý nhẹ nhàng, thích hoa dại và những buổi chiều bên hồ.",
      },
      loveStory: [
        { title: "Bên Bờ Hồ Ngọc", date: "2021", description: "Gặp nhau trong một buổi chèo thuyền kayak." },
        { title: "Đồng Điệu", date: "2023", description: "Nhận ra tâm hồn thuộc về nhau giữa đất trời bao la." },
        { title: "Cùng Nhau Đi Hết Cuộc Đời", date: "2026", description: "Hôn lễ lãng mạn bên mặt hồ trong vắt." },
      ],
    },
    events: [
      {
        id: "ev-81",
        eventName: "Hôn Lễ Bên Hồ Nước Thiên Nhiên",
        eventDate: new Date("2026-12-10T11:00:00Z"),
        lunarDate: "Ngày 02 Tháng 11 Năm Bính Ngọ",
        venueName: "HỒ TRUNG TÂM ALPINIA",
        address: "Khu Du Lịch Sinh Thái Hồ Ngọc, Ba Vì, TP. Hà Nội",
        mapUrl: "https://maps.google.com",
      },
    ],
    photos: [
      { id: "p-81", url: "/images/demo/alpine-lake-couple.jpg", caption: "Alpine Lake Cover", isCover: true },
      { id: "p-82", url: "/images/templates/template-08-alpine.png", caption: "Alpine Lake Card" },
      { id: "p-83", url: "/images/demo/couple-studio.png", caption: "Pure Waterfall" },
      { id: "p-84", url: "/images/demo/alpine-lake-couple.jpg", caption: "Chú rể Nguyễn Dương" },
      { id: "p-85", url: "/images/demo/alpine-lake-couple.jpg", caption: "Cô dâu Khánh Thy" },
    ],
    bankingPrimary: { bankCode: "MB", accountNumber: "0345678899", accountName: "NGUYEN DUONG" },
    bankingSecondary: { bankCode: "VCB", accountNumber: "0998877665", accountName: "KHANH THY" },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 09. LONG PHỤNG SUM VẦY ĐỎ ĐÔ (ANH TUẤN & THU TRANG)
  // ─────────────────────────────────────────────────────────────────────────────
  "wedding-imperial-dragon-crimson": {
    id: "demo-imperial-dragon-crimson",
    slug: "wedding-imperial-dragon-crimson",
    cardCategory: "WEDDING",
    status: "ACTIVE",
    openingEffect: "NONE",
    fallingEffect: "PETAL",
    musicUrl: "/music/xin-ma-ruoc-dau.mp3",
    isAutoPlay: true,
    primaryColor: "#6E1719",
    fontFamily: "Playfair Display",
    greetingMessage: "“TRÂN TRỌNG THÔNG BÁO LỄ THÀNH HÔN CỦA CON CHÚNG TÔI — Sự hiện diện của quý khách là niềm vinh hạnh của gia đình chúng tôi!”",
    template: { slug: "wedding-imperial-dragon-crimson" },
    categoryData: {
      cardCategory: "WEDDING",
      heroSubtitle: "LONG PHỤNG SUM VẦY",
      invitationTitle: "LỄ THÀNH HÔN & VU QUY",
      coverPhotoUrl: "/images/demo/imperial-dragon-couple.jpg",
      greeting: "“Cảm ơn tất cả tình cảm của cô dì chú bác, bạn bè và anh chị em đã dành cho Anh Tuấn & Thu Trang!”",
      groom: {
        fullName: "Nguyễn Anh Tuấn",
        shortName: "Anh Tuấn",
        birthOrder: "Trưởng nam",
        avatarUrl: "/images/demo/imperial-dragon-couple.jpg",
        parents: { fatherName: "Nguyễn Văn Quản", motherName: "Nguyễn Thị Oanh" },
        story: "Doanh nhân trẻ năng động, luôn hiếu thuận và trọn chữ nghĩa tình.",
      },
      bride: {
        fullName: "Huỳnh Thu Trang",
        shortName: "Thu Trang",
        birthOrder: "Út nữ",
        avatarUrl: "/images/demo/imperial-dragon-couple.jpg",
        parents: { fatherName: "Huỳnh Đăng Khoa", motherName: "Lê Vân Anh" },
        story: "Cô gái duyên dáng, thông minh, đảm đang tề gia nội trợ.",
      },
      loveStory: [
        { title: "Duyên Thắm Tình Nồng", date: "2019", description: "Mối tình thanh xuân đẹp đẽ thời đại học." },
        { title: "Trưởng Thành Cùng Nhau", date: "2023", description: "Cùng gầy dựng sự nghiệp và vun vén tương lai." },
        { title: "Long Phụng Sum Vầy", date: "2025", description: "Trọn vẹn câu thề non hẹn biển dưới một mái nhà." },
      ],
    },
    events: [
      {
        id: "ev-91",
        eventName: "Hôn Lễ Được Cử Hành Tại Tư Gia",
        eventDate: new Date("2025-12-19T09:00:00Z"),
        lunarDate: "Ngày 30 Tháng 10 Năm Ất Tỵ",
        venueName: "PROMEX CENTER",
        address: "Số 114 Mai Hắc Đế, Phường Lê Đại Hành, Quận Hai Bà Trưng, Hà Nội",
        mapUrl: "https://maps.google.com",
      },
    ],
    photos: [
      { id: "p-91", url: "/images/demo/imperial-dragon-couple.jpg", caption: "Long Phụng Sum Vầy Cover", isCover: true },
      { id: "p-92", url: "/images/templates/template-09-dragon.png", caption: "Thiệp Cưới Long Phụng" },
      { id: "p-93", url: "/images/demo/couple-cover.png", caption: "Uyên ương trọn đời gắn bó" },
      { id: "p-94", url: "/images/demo/imperial-dragon-couple.jpg", caption: "Chú rể Anh Tuấn" },
      { id: "p-95", url: "/images/demo/imperial-dragon-couple.jpg", caption: "Cô dâu Thu Trang" },
    ],
    bankingPrimary: { bankCode: "MB", accountNumber: "0345678910", accountName: "NGUYEN ANH TUAN" },
    bankingSecondary: { bankCode: "VCB", accountNumber: "0998877661", accountName: "HUYNH THU TRANG" },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 10. CYBER NEON GLOW PARTY (SINH NHẬT KHÁNH LINH)
  // ─────────────────────────────────────────────────────────────────────────────
  "birthday-glow-party": {
    id: "demo-birthday-glow-party",
    slug: "birthday-glow-party",
    cardCategory: "BIRTHDAY",
    status: "ACTIVE",
    openingEffect: "WAX_SEAL",
    fallingEffect: "BALLOON",
    musicUrl: "/music/everytime-we-touch.mp3",
    isAutoPlay: true,
    primaryColor: "#F97316",
    fontFamily: "Outfit",
    greetingMessage: "Đánh dấu tuổi 18 rực rỡ với đêm tiệc âm nhạc & ánh sáng Glow Party! Rất mong sự hiện diện của bạn.",
    template: { slug: "birthday-glow-party" },
    categoryData: {
      cardCategory: "BIRTHDAY",
      celebrantName: "Khánh Linh",
      age: 18,
      birthDate: new Date("2008-09-15"),
      avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop",
      greeting: "Hãy cùng đến chung vui và quẩy hết mình trong bữa tiệc sinh nhật đặc biệt này nhé!",
    },
    events: [
      {
        id: "b-ev-1",
        eventName: "Đêm Tiệc Glow Party 18th",
        eventDate: new Date("2026-09-15T18:30:00Z"),
        venueName: "The Rooftop Lounge & Sky Bar",
        address: "Tầng 19, Tòa nhà Bitexco, Bến Nghé, Quận 1, TP. HCM",
        mapUrl: "https://maps.google.com",
      },
    ],
    photos: [
      { id: "bp-1", url: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&auto=format&fit=crop", caption: "Glow Party Night", isCover: true },
      { id: "bp-2", url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop", caption: "Sweet 18" },
      { id: "bp-3", url: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&auto=format&fit=crop", caption: "Happy Moments" },
    ],
    bankingPrimary: { bankCode: "MB", accountNumber: "0909123456", accountName: "NGUYEN KHANH LINH" },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 11. HOÀNG TỬ NHỎ (ĐẦY THÁNG BÉ BƠ)
  // ─────────────────────────────────────────────────────────────────────────────
  "newborn-little-prince": {
    id: "demo-newborn-little-prince",
    slug: "newborn-little-prince",
    cardCategory: "NEWBORN",
    status: "ACTIVE",
    openingEffect: "WAX_SEAL",
    fallingEffect: "BALLOON",
    musicUrl: "/music/like-my-father.mp3",
    isAutoPlay: true,
    primaryColor: "#4169A1",
    fontFamily: "Quicksand",
    greetingMessage: "Mừng thiên thần nhỏ của gia đình tròn 1 tháng tuổi! Trân trọng kính mời quý cô chú bác đến chung vui.",
    template: { slug: "newborn-little-prince" },
    categoryData: {
      cardCategory: "NEWBORN",
      babyName: "Nguyễn Minh Khang",
      nickname: "Bé Bơ",
      gender: "BOY",
      birthDate: new Date("2026-08-10"),
      weight: "3.5",
      height: "50",
      ceremonyType: "FULL_MONTH",
      avatarUrl: "https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=600&auto=format&fit=crop",
      greeting: "Bé Bơ xin kính chào ông bà, cô chú và các bác ạ!",
    },
    events: [
      {
        id: "nb-ev-1",
        eventName: "Lễ Cúng Đầy Tháng & Tiệc Mừng",
        eventDate: new Date("2026-09-10T11:00:00Z"),
        venueName: "Trung Tâm Tiệc Cưới & Hội Nghị White Palace",
        address: "194 Hoàng Văn Thụ, Phường 9, Phú Nhuận, TP. HCM",
        mapUrl: "https://maps.google.com",
      },
    ],
    photos: [
      { id: "np-1", url: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&auto=format&fit=crop", caption: "Bé Bơ Thiên Thần", isCover: true },
      { id: "np-2", url: "https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=800&auto=format&fit=crop", caption: "Nụ cười đầu đời" },
    ],
    bankingPrimary: { bankCode: "MB", accountNumber: "0988776655", accountName: "NGUYEN MINH KHANG" },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 12. THIÊN THẦN NHỎ (THÔI NÔI BÉ DÂU TÂY)
  // ─────────────────────────────────────────────────────────────────────────────
  "newborn-sweet-angel": {
    id: "demo-newborn-sweet-angel",
    slug: "newborn-sweet-angel",
    cardCategory: "NEWBORN",
    status: "ACTIVE",
    openingEffect: "WAX_SEAL",
    fallingEffect: "BALLOON",
    musicUrl: "/music/a-thousand-years.mp3",
    isAutoPlay: true,
    primaryColor: "#E07A89",
    fontFamily: "Quicksand",
    greetingMessage: "Mừng công chúa nhỏ tròn 1 tuổi! Kính mời quý khách đến dự tiệc thôi nôi của bé.",
    template: { slug: "newborn-sweet-angel" },
    categoryData: {
      cardCategory: "NEWBORN",
      babyName: "Trần Tuệ An",
      nickname: "Bé Dâu Tây",
      gender: "GIRL",
      birthDate: new Date("2025-09-20"),
      weight: "9.2",
      height: "76",
      ceremonyType: "ONE_YEAR",
      avatarUrl: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600&auto=format&fit=crop",
      greeting: "Gia đình trân trọng kính mời quý khách đến chung vui mừng bé tròn 1 tuổi!",
    },
    events: [
      {
        id: "na-ev-1",
        eventName: "Tiệc Mừng Thôi Nôi Bé Dâu Tây",
        eventDate: new Date("2026-09-20T17:30:00Z"),
        venueName: "Nhà Hàng Riverside Palace",
        address: "360D Bến Vân Đồn, Phường 1, Quận 4, TP. HCM",
        mapUrl: "https://maps.google.com",
      },
    ],
    photos: [
      { id: "nap-1", url: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800&auto=format&fit=crop", caption: "Công chúa nhỏ Dâu Tây", isCover: true },
      { id: "nap-2", url: "https://images.unsplash.com/photo-1519689680058-324335c77eba?w=800&auto=format&fit=crop", caption: "Thiên thần nhỏ" },
    ],
    bankingPrimary: { bankCode: "VCB", accountNumber: "0345612345", accountName: "TRAN TUE AN" },
  },
};
