import { TemplateModalData } from "@/components/shared/TemplateDetailModal";

export interface MasterTemplateItem extends TemplateModalData {
  slug: string;
  originalPrice?: string;
  rating?: number;
  salesCount?: number;
}

export const MASTER_TEMPLATES: MasterTemplateItem[] = [
  // ── 01. Á ĐÔNG CUNG ĐÌNH HOÀNG GIA ──
  {
    id: "wedding-heritage-crimson-gold",
    slug: "wedding-heritage-crimson-gold",
    demoSlug: "wedding-heritage-crimson-gold",
    name: "Á Đông Cung Đình Hoàng Gia",
    category: "WEDDING",
    style: "Cổ Điển Hoàng Gia",
    price: "199.000đ",
    originalPrice: "350.000đ",
    imageUrl: "/images/templates/template-01-heritage.png",
    isNew: true,
    description: "Phong cách Á Đông cung đình với tone đỏ nhung gấm & vàng hoàng kim, phù hiệu sơn mài đỉnh thiệp, khung vòm cổ điển, huy hiệu âm dương lịch và sớ thư pháp lưu bút.",
    tags: ["Á Đông", "Sơn Mài", "Hoàng Gia"],
    features: ["Hiệu ứng phong bì sáp đỏ 3D", "Lịch âm dương Song Hỷ", "Album ảnh cưới cổ điển", "Hộp mừng cưới VietQR"],
    colorPalette: ["#8B1E2D", "#C5A059", "#FAF4EA", "#3B1B1F"],
    envelopeColor: "#8B1E2D",
    musicTitle: "Lễ Đường Tình Yêu (Nhạc cụ truyền thống)",
    coupleText: "Minh Khôi & Ngọc Hân",
    eventDateText: "20.11.2026",
    venueText: "Tư gia & Trung tâm Hội nghị Hoàng Gia",
    rating: 5,
    salesCount: 1240,
  },

  // ── 02. TẠP CHÍ HÀN QUỐC EDITORIAL ──
  {
    id: "wedding-modern-editorial-magazine",
    slug: "wedding-modern-editorial-magazine",
    demoSlug: "wedding-modern-editorial-magazine",
    name: "Tạp Chí Hàn Quốc Editorial",
    category: "WEDDING",
    style: "Minimalist Luxury",
    price: "249.000đ",
    originalPrice: "400.000đ",
    imageUrl: "/images/templates/template-02-magazine.png",
    isNew: true,
    description: "Tạp chí Hàn Quốc tone be ấm & nâu chocolate, bố cục Zigzag Song thân đối xứng, bộ 3 ảnh Triptych và tờ lịch tháng nhúng trực tiếp.",
    tags: ["Tạp Chí", "Hàn Quốc", "Zigzag"],
    features: ["Bố cục Vogue Magazine", "Lưới ảnh Triptych 3 tấm", "Timeline câu chuyện tình yêu", "RSVP xác nhận tham dự"],
    colorPalette: ["#4A3728", "#D8C7B5", "#F7F4EF", "#1C1714"],
    envelopeColor: "#D8C7B5",
    musicTitle: "Until I Found You - Stephen Sanchez",
    coupleText: "Quang Vinh & Hải Yến",
    eventDateText: "18.12.2026",
    venueText: "Park Hyatt Saigon, TP. Hồ Chí Minh",
    rating: 5,
    salesCount: 980,
  },

  // ── 03. SWEET PINK LÃNG MẠN ──
  {
    id: "wedding-sweet-editorial-romance",
    slug: "wedding-sweet-editorial-romance",
    demoSlug: "wedding-sweet-editorial-romance",
    name: "Sweet Pink Lãng Mạn",
    category: "WEDDING",
    style: "Floral Romance",
    price: "249.000đ",
    originalPrice: "380.000đ",
    imageUrl: "/images/templates/template-03-sweet-pink.png",
    isNew: true,
    description: "Tone hồng phấn khói & đất nung ngọt ngào, phong bì sáp đỏ 3D, hộp vòm Arch RSVP và cặp thẻ đôi VietQR riêng cho Cô dâu & Chú rể.",
    tags: ["Sweet Pink", "Phong Bì 3D", "VietQR"],
    features: ["Phong bì hồng pastel", "Hiệu ứng thả tim Heart Burst", "Cặp thẻ mừng VietQR đôi", "Sổ lưu bút trực tuyến"],
    colorPalette: ["#D48B96", "#E8B4B8", "#FFF5F5", "#683B43"],
    envelopeColor: "#D48B96",
    musicTitle: "I Do - 911 Band",
    coupleText: "Tuấn Anh & Mai Phương",
    eventDateText: "05.10.2026",
    venueText: "GEM Center, TP. Hồ Chí Minh",
    rating: 5,
    salesCount: 1120,
  },

  // ── 04. QUÝ TỘC ĐỎ RƯỢU MARSALA ──
  {
    id: "wedding-crimson-wine-marsala",
    slug: "wedding-crimson-wine-marsala",
    demoSlug: "wedding-crimson-wine-marsala",
    name: "Quý Tộc Đỏ Rượu Marsala",
    category: "WEDDING",
    style: "Cổ Điển Hoàng Gia",
    price: "299.000đ",
    originalPrice: "450.000đ",
    imageUrl: "/images/templates/template-04-marsala.png",
    isNew: true,
    description: "Đỏ rượu vang Burgundy & trắng kem quý tộc Châu Âu, cổng vòm La Mã chữ uốn lượn, thấu kính lịch tròn trong suốt, 2 thẻ tiệc và đếm ngược kép.",
    tags: ["Marsala", "Cổng Vòm", "Quý Tộc"],
    features: ["Cổng vòm Roman Arch", "Đếm ngược kép 2 nhà", "Thấu kính lịch tháng", "Dress code tiệc cưới"],
    colorPalette: ["#721B24", "#C69C6D", "#FAF6F0", "#2E0A0E"],
    envelopeColor: "#721B24",
    musicTitle: "A Thousand Years - Christina Perri",
    coupleText: "Đức Trọng & Thùy Chi",
    eventDateText: "12.11.2026",
    venueText: "InterContinental Landmark 72, Hà Nội",
    rating: 5,
    salesCount: 860,
  },

  // ── 05. RUSTIC XANH RÊU THIÊN NHIÊN ──
  {
    id: "wedding-forest-green-botanical",
    slug: "wedding-forest-green-botanical",
    demoSlug: "wedding-forest-green-botanical",
    name: "Rustic Xanh Rêu Thiên Nhiên",
    category: "WEDDING",
    style: "Floral Romance",
    price: "249.000đ",
    originalPrice: "390.000đ",
    imageUrl: "/images/templates/template-05-forest.png",
    isNew: true,
    description: "Tone xanh rêu rừng & hoa dại mộc mạc, phong bì thảo mộc, thẻ lịch Polaroid My Love, thơ tình đối diện và thẻ sự kiện liền khối.",
    tags: ["Rustic", "Xanh Rêu", "Sân Vườn"],
    features: ["Phong bì xanh lá thảo mộc", "Ảnh Polaroid My Love", "Lịch trình tiệc cưới", "Bản đồ chỉ đường Google Maps"],
    colorPalette: ["#2C4A34", "#B88E4C", "#F4F7F4", "#152419"],
    envelopeColor: "#2C4A34",
    musicTitle: "Perfect - Ed Sheeran",
    coupleText: "Hoàng Nam & Thảo Vy",
    eventDateText: "24.12.2026",
    venueText: "Thảo Điền Village, TP. Thủ Đức",
    rating: 5,
    salesCount: 940,
  },

  // ── 06. HOA SEN THANH KHIẾT BÁO HỶ ──
  {
    id: "wedding-pure-lotus-heritage",
    slug: "wedding-pure-lotus-heritage",
    demoSlug: "wedding-pure-lotus-heritage",
    name: "Hoa Sen Thanh Khiết Báo Hỷ",
    category: "WEDDING",
    style: "Cổ Điển Hoàng Gia",
    price: "249.000đ",
    originalPrice: "380.000đ",
    imageUrl: "/images/templates/template-06-lotus.png",
    isNew: true,
    description: "Hoa sen quốc hoa màu nước thanh tao, biểu tượng Song Hỷ son tròn, thiệp báo hỷ trang nghiêm và đầm sen dát vàng hoàng kim.",
    tags: ["Hoa Sen", "Báo Hỷ", "Thuần Việt"],
    features: ["Họa tiết Hoa Sen Thủy Mặc", "Huy hiệu Song Hỷ tròn son", "Thiệp mời song thân 2 họ", "Âm nhạc trữ tình nhẹ nhàng"],
    colorPalette: ["#A8424E", "#8DA87B", "#FAF7F2", "#4D1F25"],
    envelopeColor: "#FAF7F2",
    musicTitle: "Áo Lụa Hà Đông - Không Lời",
    coupleText: "Gia Huy & Khánh Linh",
    eventDateText: "15.01.2027",
    venueText: "Tư gia Nhà Gái & Nhà Khách Quốc Tế",
    rating: 5,
    salesCount: 790,
  },

  // ── 07. ĐIỆN ẢNH LOOKBOOK TÌNH YÊU ──
  {
    id: "wedding-cinematic-editorial",
    slug: "wedding-cinematic-editorial",
    demoSlug: "wedding-cinematic-editorial",
    name: "Điện Ảnh Lookbook Tình Yêu",
    category: "WEDDING",
    style: "Minimalist Luxury",
    price: "299.000đ",
    originalPrice: "480.000đ",
    imageUrl: "/images/templates/template-07-cinematic.png",
    isNew: true,
    description: "Phim điện ảnh & tạp chí thời trang Vogue Lookbook, nhiều chương tình yêu Our Love Story & Fall In Love, lịch nụ hôn và poster You are my Sunshine.",
    tags: ["Cinematic", "Vogue", "Lookbook"],
    features: ["Tone rạp chiếu phim sang trọng", "Love Story dạng hồi ký ảnh", "Poster điện ảnh độc bản", "Lời chúc hiệu ứng sao bay"],
    colorPalette: ["#1F1D1A", "#BE944E", "#F8F5F0", "#52473A"],
    envelopeColor: "#1F1D1A",
    musicTitle: "La La Land - City of Stars",
    coupleText: "Minh Quân & Thu Hà",
    eventDateText: "08.02.2027",
    venueText: "JW Marriott Hotel, Hà Nội",
    rating: 5,
    salesCount: 880,
  },

  // ── 08. SUỐI NGUỒN HỒ NƯỚC THIÊN NHIÊN ──
  {
    id: "wedding-alpine-lake-romance",
    slug: "wedding-alpine-lake-romance",
    demoSlug: "wedding-alpine-lake-romance",
    name: "Suối Nguồn Hồ Nước Thiên Nhiên",
    category: "WEDDING",
    style: "Minimalist Luxury",
    price: "249.000đ",
    originalPrice: "390.000đ",
    imageUrl: "/images/templates/template-08-alpine.png",
    isNew: true,
    description: "Hồ nước ngọc bích thiên nhiên Thụy Sĩ, lịch tán rừng thông, hoa khô dán Washi Tape, hộp quà pastel và cổng Song Hỷ minh họa.",
    tags: ["Hồ Nước", "Thụy Sĩ", "Washi Tape"],
    features: ["Tone xanh ngọc bích êm dịu", "Họa tiết Washi Tape hoa khô", "Đếm ngược ngày cưới", "Hộp mừng cưới trực tuyến"],
    colorPalette: ["#36656B", "#C29B63", "#F2F7F7", "#1C373B"],
    envelopeColor: "#36656B",
    musicTitle: "Can't Help Falling in Love",
    coupleText: "Đăng Khoa & Bảo Ngọc",
    eventDateText: "28.02.2027",
    venueText: "Dalat Edensee Lake Resort & Spa",
    rating: 5,
    salesCount: 710,
  },

  // ── 09. LONG PHỤNG SUM VẦY ĐỎ ĐÔ ──
  {
    id: "wedding-imperial-dragon-crimson",
    slug: "wedding-imperial-dragon-crimson",
    demoSlug: "wedding-imperial-dragon-crimson",
    name: "Long Phụng Sum Vầy Đỏ Đô",
    category: "WEDDING",
    style: "Cổ Điển Hoàng Gia",
    price: "299.000đ",
    originalPrice: "480.000đ",
    imageUrl: "/images/templates/template-09-dragon.png",
    isNew: true,
    description: "Đỏ đô gấm cung đình toàn trang in chìm Long Phụng, tranh chibi uyên ương tựa cổng Song Hỷ 3D, giá vẽ hoa cưới và hộp mừng cưới 2 thẻ QR vàng cát.",
    tags: ["Long Phụng", "Đỏ Đô", "Song Hỷ 3D"],
    features: ["Long Phụng gấm dập nổi", "Cổng Song Hỷ 3D Chibi", "Album ảnh cưới tương tác", "Thẻ QR vàng cát song đôi"],
    colorPalette: ["#82131A", "#D4AF37", "#FDF9F0", "#3E080C"],
    envelopeColor: "#82131A",
    musicTitle: "Thành Hôn Hạnh Phúc - Cổ Phong",
    coupleText: "Thành Đạt & Phương Anh",
    eventDateText: "18.03.2027",
    venueText: "Trung tâm Hội nghị White Palace, TP. Hồ Chí Minh",
    rating: 5,
    salesCount: 1350,
  },

  // ── 10. SINH NHẬT NEON GLOW PARTY ──
  {
    id: "birthday-glow-party",
    slug: "birthday-glow-party",
    demoSlug: "birthday-glow-party",
    name: "Cyber Neon Glow Party",
    category: "BIRTHDAY",
    style: "Cyber Neon",
    price: "199.000đ",
    originalPrice: "299.000đ",
    imageUrl: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=700&auto=format&fit=crop",
    isNew: true,
    description: "Phong cách tiệc sinh nhật Neon trẻ trung, hiệu ứng ánh sáng phát quang rực rỡ, tích hợp check-in quà tặng và âm nhạc sôi động.",
    tags: ["Neon", "Sinh Nhật", "Party"],
    features: ["Hiệu ứng ánh sáng Neon", "Đếm ngược giờ tiệc quẩy", "Gửi lời chúc mừng sinh nhật", "Lịch trình mini game"],
    colorPalette: ["#120826", "#FF007F", "#00F0FF", "#FFE600"],
    envelopeColor: "#120826",
    musicTitle: "Happy Birthday Remix Beat",
    coupleText: "Kevin Nguyen's 25th",
    eventDateText: "15.09.2026",
    venueText: "The Roof Lounge, Quận 1, TP. HCM",
    rating: 5,
    salesCount: 520,
  },

  // ── 11. ĐẦY THÁNG HOÀNG TỬ BÉ ──
  {
    id: "newborn-little-prince",
    slug: "newborn-little-prince",
    demoSlug: "newborn-little-prince",
    name: "Hoàng Tử Nhỏ (Đầy Tháng)",
    category: "NEWBORN",
    style: "Minimalist Luxury",
    price: "199.000đ",
    originalPrice: "299.000đ",
    imageUrl: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=700&auto=format&fit=crop",
    isNew: true,
    description: "Tone xanh pastel dịu mát cho tiệc đầy tháng, thôi nôi bé trai với hình ảnh chú gấu đáng yêu và cột mốc chào đời.",
    tags: ["Đầy Tháng", "Bé Trai", "Pastel"],
    features: ["Tone xanh baby pastel", "Thông số lúc bé chào đời", "Cây lời chúc lì xì may mắn", "RSVP xác nhận tham dự"],
    colorPalette: ["#6CA0DC", "#C5B358", "#F5F8FC", "#2F4858"],
    envelopeColor: "#6CA0DC",
    musicTitle: "Twinkle Twinkle Little Star (Music Box)",
    coupleText: "Bé Cà Rốt (Minh An)",
    eventDateText: "10.08.2026",
    venueText: "Nhà hàng Hương Sen, Hà Nội",
    rating: 5,
    salesCount: 460,
  },

  // ── 12. THÔI NÔI THIÊN THẦN NHỎ ──
  {
    id: "newborn-sweet-angel",
    slug: "newborn-sweet-angel",
    demoSlug: "newborn-sweet-angel",
    name: "Thiên Thần Nhỏ (Thôi Nôi)",
    category: "NEWBORN",
    style: "Minimalist Luxury",
    price: "199.000đ",
    originalPrice: "299.000đ",
    imageUrl: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=700&auto=format&fit=crop",
    isNew: true,
    description: "Tone hồng ngọt ngào mừng bé gái tròn 1 tuổi hoặc đầy tháng, thiết kế nhẹ nhàng trong trẻo cùng album ảnh lớn khôn của bé.",
    tags: ["Thôi Nôi", "Bé Gái", "Ngọt Ngào"],
    features: ["Tone hồng phấn công chúa", "Hành trình 12 tháng lớn khôn", "Sổ chúc phúc tuổi mới", "Hộp quà lì xì may mắn"],
    colorPalette: ["#F4C2C2", "#E8A598", "#FFF9F9", "#5A3D31"],
    envelopeColor: "#F4C2C2",
    musicTitle: "Lullaby Baby Sweet Melody",
    coupleText: "Bé Dâu Tây (Gia Hân)",
    eventDateText: "25.09.2026",
    venueText: "Khách sạn Mường Thanh Luxury, Đà Nẵng",
    rating: 5,
    salesCount: 430,
  },
];
